// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ErrorKind } from "./ErrorKind";

/**
 * IPC で送る形。`AppError` は `std::io::Error` などを抱えて直接シリアライズできないため、この形に写して送る。
 */
export type AppError = { kind: ErrorKind, message: string, };
