// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type AssetMeta = { 
/**
 * sha256（小文字 16 進）
 */
id: string, mime: string, fileName: string, size: number, };
