// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AssetMeta } from "./AssetMeta";
import type { DocMeta } from "./DocMeta";
import type { Section } from "./Section";
import type { SourceType } from "./SourceType";

export type DocDetail = { sourceHash: string, originalAssetId: string | null, assets: Array<AssetMeta>, sections: Array<Section>, id: string, title: string, sourceType: SourceType, sourcePath: string | null, meta: DocMeta, sectionCount: number, createdAt: string, updatedAt: string, };
