// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ModChannel } from "./ModChannel";
import type { ModTarget } from "./ModTarget";

export type DocMeta = { modTarget: ModTarget | null, modChannel: ModChannel | null, 
/**
 * Workshop の表記（例: 1.4.3 / 1.5.36）
 */
modVersion: string | null, 
/**
 * YYYY-MM-DD
 */
verifiedAt: string | null, 
/**
 * 読んだ ACE-Anvil のソースのコミット（小文字の 16 進 7〜40 桁）
 */
aceCommit: string | null, 
/**
 * 処理を確かめたゲーム本体の版（例: 1.8.0.13）
 */
gameVersion: string | null, tags: Array<string>, 
/**
 * ライブラリと見出しツリーでの順番（小さいほど前）。ないものはタイトル順で後ろに並ぶ
 */
order: number | null, 
/**
 * 分類。ライブラリと見出しツリーで同じ分類の原稿をまとめる。ないものは末尾の「その他」に並ぶ
 */
category: string | null, };
