// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ModChannel } from "./ModChannel";
import type { ModTarget } from "./ModTarget";

export type DocMeta = { modTarget: ModTarget | null, modChannel: ModChannel | null, 
/**
 * Workshop の表記（例: 1.4.3 / 1.5.36）
 */
modVersion: string | null, 
/**
 * YYYY-MM-DD
 */
verifiedAt: string | null, tags: Array<string>, };
