// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DocMeta } from "./DocMeta";
import type { OutlineHeading } from "./OutlineHeading";

/**
 * 全ドキュメントの見出しの一覧。ツリーのために全文書の本文の HTML を IPC で運ばないよう、見出しだけを返す。
 */
export type DocOutline = { id: string, title: string, sourcePath: string | null, meta: DocMeta, headings: Array<OutlineHeading>, };
