// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DocMeta } from "./DocMeta";
import type { SourceType } from "./SourceType";

export type DocSummary = { id: string, title: string, sourceType: SourceType, sourcePath: string | null, meta: DocMeta, sectionCount: number, createdAt: string, updatedAt: string, };
