// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DocMeta } from "./DocMeta";
import type { SectionInput } from "./SectionInput";
import type { SourceType } from "./SourceType";

/**
 * `doc_upsert` の入力。アセットは bytes を含めず、先に `asset_put` で得た id で参照する（大きなバイナリを JSON に載せないため）。
 */
export type DocUpsertInput = { title: string, sourceType: SourceType, 
/**
 * 同じ値のドキュメントがあれば置き換える
 */
sourcePath: string | null, sourceHash: string, meta: DocMeta, sections: Array<SectionInput>, assetIds: Array<string>, originalAssetId: string | null, };
