// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * TS 側で分岐に使うエラーの種類。文字列リテラルの union として生成される。
 */
export type ErrorKind = "io" | "not_found" | "invalid_input" | "internal";
