// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type FlowHit = { 
/**
 * フローの id（スラッグ）
 */
id: string, title: string, 
/**
 * `SectionHit.snippet` と同じ形（U+E000 / U+E001 で強調）。ノードの文から作る
 */
snippet: string, 
/**
 * 大きいほど上位。LIKE の当たり方で付けるので、節の score とは比べられない
 */
score: number, 
/**
 * 入力した語そのものは含まず、同義語だけでヒットした
 */
synonymOnly: boolean, };
