// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { HotkeyAction } from "./HotkeyAction";

export type HotkeyBinding = { action: HotkeyAction, 
/**
 * `Ctrl+Shift+M` の形
 */
accelerator: string, defaultAccelerator: string, 
/**
 * 登録に失敗したときの理由（他のアプリが使っているなど）。登録できていれば null
 */
error: string | null, };
