// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * ACE の版。`None`（DB では NULL）は「版を問わない / 不明」。
 */
export type ModChannel = "release" | "dev";
