// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * 原稿が前提にしている ACE Medical のモジュール。
 * Release と Dev で公開されているモジュールが違うが、この値で両方の版を過不足なく表せる。
 */
export type ModTarget = "core" | "hitzones" | "circulation" | "breathing" | "defibrillation" | "ai" | "general";
