// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * 原稿が前提にしている ACE Medical のモジュール（dev-docs/reference/ace-medical-notes.md）。
 */
export type ModTarget = "core" | "hitzones" | "circulation" | "breathing" | "defibrillation" | "ai" | "general";
