// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ModTarget } from "./ModTarget";

/**
 * ビューアの左のツリーに出す見出し（h1〜h3）。
 */
export type OutlineHeading = { level: number, title: string, anchor: string, 
/**
 * 設定の「使っている MOD」に合わない見出しをツリーから外すため
 */
mods: Array<ModTarget>, withoutMods: Array<ModTarget>, };
