// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * ビューアの左のツリーに出す見出し（h1〜h3）。
 */
export type OutlineHeading = { level: number, title: string, anchor: string, };
