// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Rust から小窓へ送る、呼び出しのモード（イベント `overlay-mode`）。
 */
export type OverlayMode = "view" | "search" | "triage";
