// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * お気に入り・履歴の対象。節は同期で INTEGER の id が振り直されるので、文書の id とアンカーで指す。
 */
export type PrefTarget = { "kind": "section", documentId: string, anchor: string, } | { "kind": "document", documentId: string, } | { "kind": "flow", flowId: string, } | { "kind": "quickref", rowId: string, };
