// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PrefTarget } from "./PrefTarget";

/**
 * お気に入り・履歴の一覧の 1 行。対象が今も DB にあるものだけを返す。
 */
export type PrefItem = { target: PrefTarget, 
/**
 * 節の題名 / 文書の題名 / フローの題名
 */
title: string, 
/**
 * どこにあるか（節なら文書の題名）。なければ null
 */
context: string | null, 
/**
 * お気に入りに入れた日時、または最後に開いた日時（UTC の ISO 8601）
 */
at: string, };
