// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ModTarget } from "./ModTarget";

export type QuickrefHit = { 
/**
 * 行の id（スラッグ）
 */
id: string, 
/**
 * 症状
 */
title: string, category: string, 
/**
 * 1=軽度 2=中等度 3=重度 4=致命的
 */
severity: number, 
/**
 * 表示条件（結果の説明に出す。検索は設定の「使っている MOD」では絞らないため）
 */
mods: Array<ModTarget>, withoutMods: Array<ModTarget>, 
/**
 * `SectionHit.snippet` と同じ形（U+E000 / U+E001 で強調）。手順・物品・備考から作る
 */
snippet: string, 
/**
 * 大きいほど上位。LIKE の当たり方で付けるので、節の score とは比べられない
 */
score: number, 
/**
 * 入力した語そのものは含まず、同義語だけでヒットした
 */
synonymOnly: boolean, };
