// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ModChannel } from "./ModChannel";
import type { QuickrefRow } from "./QuickrefRow";

/**
 * `quickref_replace_all` の入力。同梱ファイル 1 つ分で、全行を置き換える。
 */
export type QuickrefReplaceInput = { sourceHash: string, modChannel: ModChannel | null, 
/**
 * YYYY-MM-DD
 */
verifiedAt: string | null, 
/**
 * ファイルに書いた順
 */
rows: Array<QuickrefRow>, };
