// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ModTarget } from "./ModTarget";

/**
 * クイック表の 1 行。形の検査は TS の zod で行い、Rust は DB に入れてよい最低限を確かめる。
 */
export type QuickrefRow = { 
/**
 * スラッグ。お気に入りと `quickref:<id>` のリンクで使う
 */
id: string, category: string, symptom: string, 
/**
 * 1=軽度 2=中等度 3=重度 4=致命的
 */
severity: number, 
/**
 * 手順（1 要素 1 動作）
 */
treatment: Array<string>, items: Array<string>, notes: string | null, 
/**
 * `doc:<ファイル名>#<anchor>` / `flow:<id>` / `quickref:<id>` / `https://…`
 */
links: Array<string>, 
/**
 * この MOD をすべて入れているときだけ出す
 */
mods: Array<ModTarget>, 
/**
 * この MOD をどれも入れていないときだけ出す
 */
withoutMods: Array<ModTarget>, };
