// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ModChannel } from "./ModChannel";
import type { QuickrefRow } from "./QuickrefRow";

export type QuickrefTable = { 
/**
 * まだ一度も同期していなければ null（起動時の同期で「変更なし」を判定するため）
 */
sourceHash: string | null, modChannel: ModChannel | null, verifiedAt: string | null, 
/**
 * ファイルに書いた順
 */
rows: Array<QuickrefRow>, };
