// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SectionHit } from "./SectionHit";

/**
 * 横断検索の結果。Step 06 / 07 でクイック表とフローの種類を足す。
 */
export type SearchHit = { "kind": "section" } & SectionHit;
