// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { FlowHit } from "./FlowHit";
import type { SectionHit } from "./SectionHit";

/**
 * 横断検索の結果。Step 06 でクイック表の種類を足す。
 */
export type SearchHit = { "kind": "section" } & SectionHit | { "kind": "flow" } & FlowHit;
