// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ModChannel } from "./ModChannel";
import type { ModTarget } from "./ModTarget";

/**
 * 検索の絞り込み。省略した条件は掛けない。
 */
export type SearchFilter = { 
/**
 * いずれかに一致
 */
modTargets?: Array<ModTarget>, 
/**
 * 指定した版か、版を問わない（NULL）ドキュメント
 */
modChannel?: ModChannel, 
/**
 * ドキュメントかセクションに、すべてのタグが付いている
 */
tags?: Array<string>, };
