// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { FlowHit } from "./FlowHit";
import type { QuickrefHit } from "./QuickrefHit";
import type { SectionHit } from "./SectionHit";

/**
 * 横断検索の結果。
 */
export type SearchHit = { "kind": "section" } & SectionHit | { "kind": "flow" } & FlowHit | { "kind": "quickref" } & QuickrefHit;
