// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type SectionInput = { 
/**
 * 0 = 見出し前の導入部、1〜6
 */
level: number, title: string, 
/**
 * ドキュメント内で一意
 */
anchor: string, 
/**
 * `DOMPurify` で無害化済みの HTML
 */
html: string, plainText: string, 
/**
 * PDF のページ番号（1 始まり）
 */
page: number | null, 
/**
 * 本文にない語でも検索に掛けるためのタグ
 */
tags: Array<string>, };
