// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ModTarget } from "./ModTarget";

export type Section = { id: number, parentId: number | null, level: number, title: string, anchor: string, orderIndex: number, html: string, plainText: string, page: number | null, tags: Array<string>, mods: Array<ModTarget>, withoutMods: Array<ModTarget>, };
