// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type SectionHit = { 
/**
 * セクションの id
 */
id: number, title: string, 
/**
 * 強調部分を U+E000（開始）と U+E001（終了）で囲んだ本文の抜粋。HTML ではない
 */
snippet: string, 
/**
 * 大きいほど上位
 */
score: number, documentId: string, documentTitle: string, anchor: string, 
/**
 * 入力した語そのものは含まず、同義語だけでヒットした
 */
synonymOnly: boolean, 
/**
 * この節に実際に含まれていた語（同義語で広げた候補を含む）。開いた先で検索語をハイライトするのに使う
 */
matchedTerms: Array<string>, };
