// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type SynonymGroup = { id: number, terms: Array<string>, note: string | null, updatedAt: string, };
