// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * `id` が null なら新規作成、あれば置き換え。
 */
export type SynonymGroupInput = { id: number | null, terms: Array<string>, note: string | null, };
