// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ModChannel } from "./ModChannel";
import type { ModTarget } from "./ModTarget";

export type TriageSummary = { id: string, title: string, description: string | null, modTargets: Array<ModTarget>, modChannel: ModChannel | null, verifiedAt: string | null, version: number, 
/**
 * 起動時の同期で「変更なし」を判定するために一覧でも返す
 */
sourceHash: string, updatedAt: string, };
