// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ModChannel } from "./ModChannel";
import type { ModTarget } from "./ModTarget";

/**
 * `triage_upsert` の入力。一覧・絞り込み・検索に使う値は、TS がフローの JSON から写して渡す
 * （Rust がフローの形を解釈せずに済むようにするため。形の検査は TS の zod と validate.ts で行う）。
 */
export type TriageUpsertInput = { 
/**
 * スラッグ。同じ id のフローがあれば置き換える
 */
id: string, title: string, description: string | null, modTargets: Array<ModTarget>, modChannel: ModChannel | null, 
/**
 * YYYY-MM-DD
 */
verifiedAt: string | null, version: number, 
/**
 * フロー全体の JSON（triage-format.md）
 */
json: string, 
/**
 * ノードの文などを改行でつないだもの（検索用）
 */
searchText: string, sourceHash: string, };
